## NOTEBOOK- Análise Exploratória do Dataset de Inadimplência

### Importação das bibliotecas

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from ucimlrepo import fetch_ucirepo

### Carregamento de dataset

In [ ]:
dataset = fetch_ucirepo(id=350)

# Features
X = dataset.data.features

# Target
y = dataset.data.targets

print("Features:")
display(X.head())
print("\nTarget:")
display(y.head())

### dimensão dados

In [ ]:
print("Dimensão das features:", X.shape)
print("Dimensão do target:", y.shape)

### identificação das colunas e tipos

In [ ]:
print("Colunas das features:")
print(X.columns.tolist())
display(dataset.variables)

print("Tipos das features:")
print(X.dtypes)

print("\nTipo do target:")
print(y.dtypes)

### informação geral

In [ ]:
X.info()

y.info()

### valores ausentes

In [ ]:
print("Valores ausentes por coluna:")
display(X.isnull().sum())
print("Total de valores ausentes:", X.isnull().sum().sum())
print("Valores ausentes no target:", y.isnull().sum().sum())

### registros duplicados

In [31]:
print("Duplicatas em X:", X.duplicated().sum())

dados = X.copy()
dados["Y"] = y.iloc[:, 0]
print("Duplicatas completas:", dados.duplicated().sum())

Duplicatas em X: 56
Duplicatas completas: 35

### duplicações nas features

In [32]:
duplicados_X = dados[
    dados.duplicated(subset=X.columns, keep=False)
]

print(
    "Registros envolvidos em duplicações de X:",
    len(duplicados_X)
)

display(
    duplicados_X
    .sort_values(by=X.columns.tolist())
    .head(20)
)

Registros envolvidos em duplicações de X: 108

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
12430,20000,1,2,2,24,2,2,4,4,4,...,1650,1650,1650,0,0,0,0,0,0,1
12432,20000,1,2,2,24,2,2,4,4,4,...,1650,1650,1650,0,0,0,0,0,0,0
14294,20000,1,2,2,24,2,2,4,4,4,...,1650,1650,1650,0,0,0,0,0,0,1
1759,50000,1,2,2,26,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
10250,50000,1,2,2,26,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
7170,50000,2,1,2,23,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
17032,50000,2,1,2,23,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
291,50000,2,2,2,22,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,1
8297,50000,2,2,2,22,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
1983,80000,1,1,2,37,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,1
8871,80000,1,1,2,37,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
17879,80000,1,3,2,27,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,1
29316,80000,1,3,2,27,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
7366,80000,2,2,1,31,-2,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
19114,80000,2,2,1,31,-2,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
21768,80000,2,2,2,25,-2,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
27765,80000,2,2,2,25,-2,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
6785,80000,2,3,1,42,-2,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
28983,80000,2,3,1,42,-2,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
22726,90000,2,1,2,31,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0

### X iguais, mas Y diferentes

In [33]:
grupos = (
    dados
    .groupby(X.columns.tolist())["Y"]
    .nunique()
)

print(
    "Grupos de X idênticos com Y diferente:",
    (grupos > 1).sum()
)

Grupos de X idênticos com Y diferente: 21

### estatisticas descritivas

In [ ]:
display(X.describe().T)

### variáveis categóricas

In [ ]:
#X2 → sexo
#X3 → educação
#X4 → estado civil

for coluna in ["X2", "X3", "X4"]:
    print(f"\n{coluna}")
    display(
        X[coluna]
        .value_counts()
        .sort_index()
    )

### histórico de pagamento

In [34]:
colunas_pagamento = [
    "X6",
    "X7",
    "X8",
    "X9",
    "X10",
    "X11"
]

for coluna in colunas_pagamento:
    print(f"\n{coluna}")
    display(
        X[coluna]
        .value_counts()
        .sort_index()
    )

X6

X6
-2     2759
-1     5686
 0    14737
 1     3688
 2     2667
 3      322
 4       76
 5       26
 6       11
 7        9
 8       19
Name: count, dtype: int64

X7

X7
-2     3782
-1     6050
 0    15730
 1       28
 2     3927
 3      326
 4       99
 5       25
 6       12
 7       20
 8        1
Name: count, dtype: int64

X8

X8
-2     4085
-1     5938
 0    15764
 1        4
 2     3819
 3      240
 4       76
 5       21
 6       23
 7       27
 8        3
Name: count, dtype: int64

X9

X9
-2     4348
-1     5687
 0    16455
 1        2
 2     3159
 3      180
 4       69
 5       35
 6        5
 7       58
 8        2
Name: count, dtype: int64

X10

X10
-2     4546
-1     5539
 0    16947
 2     2626
 3      178
 4       84
 5       17
 6        4
 7       58
 8        1
Name: count, dtype: int64

X11

X11
-2     4895
-1     5740
 0    16286
 2     2766
 3      184
 4       49
 5       13
 6       19
 7       46
 8        2
Name: count, dtype: int64

### Variáveis financeiras

In [35]:
colunas_faturas = [
    "X12",
    "X13",
    "X14",
    "X15",
    "X16",
    "X17"
]

colunas_pagamentos = [
    "X18",
    "X19",
    "X20",
    "X21",
    "X22",
    "X23"
]

display(X[colunas_faturas].describe().T)
display(X[colunas_pagamentos].describe().T)

,count,mean,std,min,25%,50%,75%,max
X12,30000.0,51223.330900,73635.860576,-165580.0,3558.75,22381.5,67091.00,964511.0
X13,30000.0,49179.075167,71173.768783,-69777.0,2984.75,21200.0,64006.25,983931.0
X14,30000.0,47013.154800,69349.387427,-157264.0,2666.25,20088.5,60164.75,1664089.0
X15,30000.0,43262.948967,64332.856134,-170000.0,2326.75,19052.0,54506.00,891586.0
X16,30000.0,40311.400967,60797.155770,-81334.0,1763.00,18104.5,50190.50,927171.0
X17,30000.0,38871.760400,59554.107537,-339603.0,1256.00,17071.0,49198.25,961664.0

,count,mean,std,min,25%,50%,75%,max
X18,30000.0,5663.580500,16563.280354,0.0,1000.00,2100.0,5006.00,873552.0
X19,30000.0,5921.163500,23040.870402,0.0,833.00,2009.0,5000.00,1684259.0
X20,30000.0,5225.681500,17606.961470,0.0,390.00,1800.0,4505.00,896040.0
X21,30000.0,4826.076867,15666.159744,0.0,296.00,1500.0,4013.25,621000.0
X22,30000.0,4799.387633,15278.305679,0.0,252.50,1500.0,4031.50,426529.0
X23,30000.0,5215.502567,17777.465775,0.0,117.75,1500.0,4000.00,528666.0

### valores negativos nas faturas

In [36]:
for coluna in colunas_faturas:
    negativos = (X[coluna] < 0).sum()

    print(
        f"{coluna}: {negativos} valores negativos"
    )


for coluna in colunas_faturas:

    negativos = X.loc[
        X[coluna] < 0,
        coluna
    ]

    print(
        f"\n{coluna}"
    )

    print(
        f"Quantidade: {len(negativos)}"
    )

    print(
        f"Mínimo: {negativos.min()}"
    )

    print(
        f"Mediana: {negativos.median()}"
    )

    print(
        f"Máximo: {negativos.max()}"
    )

X12: 590 valores negativos
X13: 669 valores negativos
X14: 655 valores negativos
X15: 675 valores negativos
X16: 655 valores negativos
X17: 688 valores negativos

X12
Quantidade: 590
Mínimo: -165580
Mediana: -90.5
Máximo: -1

X13
Quantidade: 669
Mínimo: -69777
Mediana: -123.0
Máximo: -1

X14
Quantidade: 655
Mínimo: -157264
Mediana: -150.0
Máximo: -1

X15
Quantidade: 675
Mínimo: -170000
Mediana: -155.0
Máximo: -1

X16
Quantidade: 655
Mínimo: -81334
Mediana: -200.0
Máximo: -1

X17
Quantidade: 688
Mínimo: -339603
Mediana: -202.5
Máximo: -1

### clientes com fatura negativa

In [37]:
tem_negativo = (
    X[colunas_faturas] < 0
).any(axis=1)

print(
    "Clientes com pelo menos uma fatura negativa:",
    tem_negativo.sum()
)

print(
    "Percentual:",
    tem_negativo.mean() * 100
)


quantidade_negativos = (
    X[colunas_faturas] < 0
).sum(axis=1)

display(
    quantidade_negativos
    .value_counts()
    .sort_index()
)

Clientes com pelo menos uma fatura negativa: 1930
Percentual: 6.433333333333334

0    28070
1      993
2      412
3      240
4      118
5       79
6       88
Name: count, dtype: int64

### valores extremos em faturas

In [43]:
for coluna in colunas_faturas:

    print(f"\n{coluna} - menores valores:")

    display(
        X[coluna]
        .nsmallest(10)
    )
    print(f"\n{coluna} - maiores valores:")
    display(
            X[coluna]
            .nlargest(10)
        )

X12 - menores valores:

12330   -165580
23003   -154973
8835     -15308
351      -14386
29779    -11545
27465    -10682
4635      -9802
4439      -9095
17204     -8187
3105      -7438
Name: X12, dtype: int64

X12 - maiores valores:

2197     964511
27557    746814
26547    653062
6912     630458
28142    626648
11557    621749
27498    613860
14553    610723
26227    608594
10780    604019
Name: X12, dtype: int64

X13 - menores valores:

21729   -69777
25862   -67526
8835    -33350
4439    -30000
19366   -26214
1650    -24704
4481    -24702
11853   -22960
21113   -18618
5296    -18088
Name: X13, dtype: int64

X13 - maiores valores:

2197     983931
19748    743970
26547    671563
6912     646770
26227    624475
10780    605943
8229     597793
28142    586825
28624    581775
21381    577681
Name: X13, dtype: int64

X14 - menores valores:

18115   -157264
18876    -61506
29491    -46127
8347     -34041
21235    -25443
27271    -24702
12923    -20320
28719    -17706
19139    -15910
9409     -15641
Name: X14, dtype: int64

X14 - maiores valores:

5296     1664089
25731     855086
6912      693131
26593     689643
26547     689627
26227     632041
8229      597415
3343      578971
22850     577957
21381     577015
Name: X14, dtype: int64

X15 - menores valores:

3183    -170000
8355     -81334
24856    -65167
29491    -50616
21235    -46627
8347     -34503
27327    -27490
12615    -24303
23466    -22108
12923    -20320
Name: X15, dtype: int64

X15 - maiores valores:

2197     891586
26547    706864
40       628699
24118    616836
20892    572805
8229     569034
21381    565669
22850    563543
23377    548020
6        542653
Name: X15, dtype: int64

X16 - menores valores:

23326   -81334
26670   -61372
29491   -53007
21235   -46627
14548   -37594
17970   -36156
24170   -30481
37      -28335
12316   -23003
15137   -20753
Name: X16, dtype: int64

X16 - maiores valores:

2197     927171
20892    823540
28405    587067
8229     551702
13782    547880
23377    530672
21381    524315
25146    516139
24686    514114
27440    508213
Name: X16, dtype: int64

X17 - menores valores:

290     -339603
26097   -209051
12828   -150953
29491    -94625
28919    -73895
27080    -57060
12388    -51443
3525     -51183
21235    -46627
5548     -45734
Name: X17, dtype: int64

X17 - maiores valores:

2197     961664
1508     699944
8229     568638
1992     527711
5035     527566
25146    514975
10960    513798
5333     511905
20892    501370
24686    499100
Name: X17, dtype: int64

### Variável alvo

In [ ]:
print("Distribuição do target:")

display(
    y.value_counts()
)

print("Proporção do target:")

display(
    y.value_counts(normalize=True) * 100
)

### visualização das variáveis

#### Variável alvo

In [ ]:
y.value_counts().plot(
    kind="bar"
)

plt.title("Distribuição da inadimplência")
plt.xlabel("Default")
plt.ylabel("Quantidade")

plt.show()

#### variáveis numéricas

In [ ]:
plt.figure(figsize=(8, 5))

X["X1"].hist(bins=30)

plt.title("Distribuição do limite de crédito")
plt.xlabel("Limite de crédito")
plt.ylabel("Quantidade")

plt.show()

In [ ]:
plt.figure(figsize=(8, 5))

X["X5"].hist(bins=30)

plt.title("Distribuição da idade")
plt.xlabel("Idade")
plt.ylabel("Quantidade")

plt.show()

#### Variáveis financeiras

In [ ]:
plt.figure(figsize=(10, 6))

X[colunas_faturas].boxplot()

plt.title("Distribuição dos valores das faturas")
plt.ylabel("Valor")

plt.show()


plt.figure(figsize=(10, 6))

X[colunas_pagamentos].boxplot()

plt.title("Distribuição dos pagamentos anteriores")
plt.ylabel("Valor")

plt.show()

### Correlção

In [ ]:
correlacao = X.corr()

display(correlacao)

plt.figure(figsize=(12, 10))

plt.imshow(
    correlacao,
    aspect="auto"
)

plt.colorbar()

plt.xticks(
    range(len(correlacao.columns)),
    correlacao.columns,
    rotation=90
)

plt.yticks(
    range(len(correlacao.columns)),
    correlacao.columns
)

plt.title("Matriz de correlação")

plt.show()